"""Sustainable Web Design model, version 3 (MASTERSPEC §7.1).

A direct port of CO2.js 0.19.0's ``SustainableWebDesign`` v3 class. Constants
live in :mod:`app.carbon.constants`; nothing numeric is written here.

The port is deliberately literal — same component split, same ordering, same
caching arithmetic — because :mod:`tests.test_swd_parity` asserts our output
matches fixtures generated by running CO2.js itself, to within 0.1%.

Model shape
-----------
``bytes -> GB -> kWh -> grams``

1. ``kWh = bytes / 1e9 * 0.81``
2. Split across four segments: device 52%, network 14%, data centre 15%,
   production 19%.
3. Multiply each segment by a grid intensity in gCO2e/kWh. Every segment uses
   the global average (472.94) except the data-centre segment when the host is
   green, which uses the renewables figure (50).

``per_visit`` additionally applies the model's caching assumption: 75% of views
are first-time and download everything; 25% are returning and re-download 2%.

Reference: CO2.js ``dist/esm/sustainable-web-design-v3.js``.
"""

from __future__ import annotations

from typing import Final

from app.carbon.constants import (
    DATACENTER_ENERGY,
    END_USER_DEVICE_ENERGY,
    FIRST_TIME_VIEWING_PERCENTAGE,
    GIGABYTE,
    GLOBAL_GRID_INTENSITY,
    KWH_PER_GB,
    NETWORK_ENERGY,
    PERCENTAGE_OF_DATA_LOADED_ON_SUBSEQUENT_LOAD,
    PRODUCTION_ENERGY,
    RENEWABLES_GRID_INTENSITY,
    RETURNING_VISITOR_PERCENTAGE,
    SWDM_V3_RATINGS,
)

__all__ = [
    "MODEL_VERSION",
    "co2_by_component",
    "energy_per_byte",
    "energy_per_byte_by_component",
    "energy_per_visit_by_component",
    "per_byte",
    "per_visit",
    "rating",
    "segment_shares",
]

MODEL_VERSION: Final[str] = "3"

# Segment name -> share of total system energy. Order matches CO2.js so that
# float summation happens in the same sequence.
_SEGMENTS: Final[tuple[tuple[str, float], ...]] = (
    ("consumerDeviceEnergy", END_USER_DEVICE_ENERGY),
    ("networkEnergy", NETWORK_ENERGY),
    ("productionEnergy", PRODUCTION_ENERGY),
    ("dataCenterEnergy", DATACENTER_ENERGY),
)


def segment_shares() -> dict[str, float]:
    """The four energy shares, for surfacing in ``CarbonResult.assumptions``."""
    return dict(_SEGMENTS)


def energy_per_byte_by_component(transfer_bytes: float) -> dict[str, float]:
    """Energy in kWh for `transfer_bytes`, split by system component.

    Mirrors ``energyPerByteByComponent``.
    """
    if transfer_bytes < 1:
        transfer_bytes = 0.0
    gigabytes = transfer_bytes / GIGABYTE
    total_kwh = gigabytes * KWH_PER_GB
    return {name: total_kwh * share for name, share in _SEGMENTS}


def energy_per_byte(transfer_bytes: float) -> float:
    """Total kWh for `transfer_bytes`. Mirrors ``energyPerByte``."""
    return sum(energy_per_byte_by_component(transfer_bytes).values())


def co2_by_component(
    energy_by_component: dict[str, float],
    *,
    green: bool = False,
) -> dict[str, float]:
    """Convert per-component kWh into per-component grams CO2e.

    Mirrors ``co2byComponent``. Only the data-centre segment changes when the
    host is green: the device, network and production segments run on whatever
    grid their hardware sits on, which a green host does not influence.

    Keys may carry a ``" - first"`` / ``" - subsequent"`` suffix (the perVisit
    path); matching is on the prefix, exactly as CO2.js does.
    """
    data_centre_intensity = RENEWABLES_GRID_INTENSITY if green else GLOBAL_GRID_INTENSITY

    result: dict[str, float] = {}
    for key, value in energy_by_component.items():
        if key.startswith("dataCenterEnergy"):
            intensity = data_centre_intensity
        else:
            # consumerDeviceEnergy, networkEnergy and productionEnergy all use
            # the global average.
            intensity = GLOBAL_GRID_INTENSITY
        result[key.replace("Energy", "CO2")] = value * intensity
    return result


def per_byte(transfer_bytes: float, *, green: bool = False) -> float:
    """Grams CO2e for a raw byte count, with no caching assumption.

    Mirrors ``perByte``. This is the figure to use for "a first visit downloads
    everything".
    """
    energy = energy_per_byte_by_component(transfer_bytes)
    return sum(co2_by_component(energy, green=green).values())


def energy_per_visit_by_component(
    transfer_bytes: float,
    *,
    first_view: float = FIRST_TIME_VIEWING_PERCENTAGE,
    return_view: float = RETURNING_VISITOR_PERCENTAGE,
    data_reload_ratio: float = PERCENTAGE_OF_DATA_LOADED_ON_SUBSEQUENT_LOAD,
) -> dict[str, float]:
    """Per-component kWh with the caching assumption applied.

    Mirrors ``energyPerVisitByComponent``: each component is split into a
    first-visit share and a much smaller subsequent-visit share.
    """
    base = energy_per_byte_by_component(transfer_bytes)
    adjusted: dict[str, float] = {}
    for key, value in base.items():
        adjusted[f"{key} - first"] = value * first_view
        adjusted[f"{key} - subsequent"] = value * return_view * data_reload_ratio
    return adjusted


def per_visit(
    transfer_bytes: float,
    *,
    green: bool = False,
    first_view: float = FIRST_TIME_VIEWING_PERCENTAGE,
    return_view: float = RETURNING_VISITOR_PERCENTAGE,
    data_reload_ratio: float = PERCENTAGE_OF_DATA_LOADED_ON_SUBSEQUENT_LOAD,
) -> float:
    """Grams CO2e per average page view. Mirrors ``perVisit``.

    This is ``CarbonResult.grams_per_view``, and the value the rating bands in
    :func:`rating` are calibrated against.
    """
    energy = energy_per_visit_by_component(
        transfer_bytes,
        first_view=first_view,
        return_view=return_view,
        data_reload_ratio=data_reload_ratio,
    )
    return sum(co2_by_component(energy, green=green).values())


def grams_return_visit(transfer_bytes: float, *, green: bool = False) -> float:
    """Grams for a single returning visitor, who re-downloads only a fraction."""
    return per_byte(transfer_bytes * PERCENTAGE_OF_DATA_LOADED_ON_SUBSEQUENT_LOAD, green=green)


def rating(grams: float) -> str:
    """Map grams-per-view to a Sustainable Web Design grade.

    Mirrors ``outputRating`` with the v3 band table. Bands are inclusive upper
    bounds, matching CO2.js's ``lessThanEqualTo``.
    """
    for grade in ("A+", "A", "B", "C", "D", "E"):
        if grams <= SWDM_V3_RATINGS[grade]:
            return grade
    return "F"
