#!/usr/bin/env python3
"""Generate frontend/src/lib/types.ts from backend/app/models.py (CLAUDE.md).

The pydantic models are the single source of truth for every structure the API
serves. This script asks pydantic for their JSON Schema and renders it as
TypeScript, so the frontend mirror cannot drift: a backend test fails if the
committed file differs from what this script would write.

Rules of the rendering:

* Every ``StrEnum`` becomes a string-literal union; every model an interface.
* Response models: the API serialises every field, defaults included (it
  never uses ``exclude_unset`` or ``exclude_none``), so every field is
  required in TypeScript; a nullable one is typed ``T | null``. Only request
  bodies (:data:`INPUT_MODELS`) have optional fields: the ones with defaults.
* ``dict`` keyed by an enum becomes ``Partial<Record<Enum, V>>``, because the
  API only sends the keys it has.

Usage:
    python scripts/gen_ts_types.py           # write the file
    python scripts/gen_ts_types.py --check   # exit 1 if it is out of date
"""

from __future__ import annotations

import argparse
import inspect
import json
import re
import sys
from enum import Enum
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND = REPO_ROOT / "backend"
OUTPUT = REPO_ROOT / "frontend" / "src" / "lib" / "types.ts"

if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from pydantic import BaseModel  # noqa: E402
from pydantic.json_schema import models_json_schema  # noqa: E402

from app import models  # noqa: E402

#: Request bodies: here a defaulted field may be omitted by the client.
INPUT_MODELS: frozenset[str] = frozenset({"ScanRequest", "PatchRequest"})

#: SSE event name -> payload model (MASTERSPEC §12). Rendered as a map type so
#: the frontend's EventSource handler is typed by event name.
SSE_EVENTS: dict[str, str] = {"step": "StepEvent", "done": "DoneEvent", "error": "ApiError"}

HEADER = """\
// AUTO-GENERATED by scripts/gen_ts_types.py from backend/app/models.py.
// Do not edit by hand: change the pydantic model, then run `make types`.
// A backend test fails if this file is out of date.
"""

_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def exported_models() -> tuple[list[type[BaseModel]], list[type[Enum]]]:
    """Public models and enums defined in app.models, in source order."""
    found_models: list[type[BaseModel]] = []
    found_enums: list[type[Enum]] = []
    for name, value in vars(models).items():
        if name.startswith("_") or not inspect.isclass(value):
            continue
        if value.__module__ != models.__name__:
            continue
        if issubclass(value, BaseModel):
            found_models.append(value)
        elif issubclass(value, Enum):
            found_enums.append(value)
    return found_models, found_enums


def build_schema() -> dict[str, Any]:
    model_list, _ = exported_models()
    _, top = models_json_schema(
        [(model, "serialization") for model in model_list],
        ref_template="#/$defs/{model}",
    )
    return top.get("$defs", {})


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _wrap(ts: str) -> str:
    return f"({ts})" if " | " in ts else ts


def ts_type(schema: dict[str, Any]) -> str:
    """Render one JSON Schema node as a TypeScript type expression."""
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            parts: list[str] = []
            for option in schema[key]:
                rendered = ts_type(option)
                if rendered not in parts:
                    parts.append(rendered)
            return " | ".join(parts)

    kind = schema.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_type({**schema, "type": item}) for item in kind)
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"{_wrap(ts_type(schema.get('items', {})))}[]"
    if kind == "object":
        values = schema.get("additionalProperties")
        value_ts = ts_type(values) if isinstance(values, dict) else "unknown"
        keys = schema.get("propertyNames")
        if isinstance(keys, dict) and ("$ref" in keys or "enum" in keys):
            return f"Partial<Record<{ts_type(keys)}, {value_ts}>>"
        return f"Record<string, {value_ts}>"
    return "unknown"


_RST_ROLE = re.compile(r":(?:func|class|data|mod|meth|attr):`~?([^`]+)`")


def _doc(text: str | None, indent: str = "") -> list[str]:
    """First paragraph of a docstring as a JSDoc block, reST markup removed."""
    if not text:
        return []
    paragraph = text.strip().split("\n\n", 1)[0]
    paragraph = _RST_ROLE.sub(lambda m: f"`{m.group(1).rsplit('.', 1)[-1]}`", paragraph)
    paragraph = paragraph.replace("``", "`")
    lines = [line.strip() for line in paragraph.splitlines() if line.strip()]
    if not lines:
        return []
    if len(lines) == 1:
        return [f"{indent}/** {lines[0]} */"]
    return [f"{indent}/**", *(f"{indent} * {line}" for line in lines), f"{indent} */"]


def render_interface(name: str, schema: dict[str, Any]) -> list[str]:
    required = set(schema.get("required", []))
    is_input = name in INPUT_MODELS
    out = [*_doc(schema.get("description")), f"export interface {name} {{"]
    for prop, prop_schema in schema.get("properties", {}).items():
        always_present = not is_input or prop in required
        key = prop if _IDENTIFIER.match(prop) else json.dumps(prop)
        optional = "" if always_present else "?"
        out.append(f"  {key}{optional}: {ts_type(prop_schema)};")
    out.append("}")
    return out


def render() -> str:
    defs = build_schema()
    _, enums = exported_models()
    enum_names = {enum.__name__ for enum in enums}

    blocks: list[list[str]] = []
    for name in sorted(defs):
        schema = defs[name]
        if name in enum_names or ("enum" in schema and "properties" not in schema):
            blocks.append(
                [*_doc(schema.get("description")), f"export type {name} = {ts_type(schema)};"]
            )
        else:
            blocks.append(render_interface(name, schema))

    missing = [model for model in SSE_EVENTS.values() if model not in defs]
    if missing:
        raise SystemExit(f"SSE payload models missing from app.models: {missing}")
    event_map = [
        "/** SSE events on GET /api/scans/{id}/events, by event name (MASTERSPEC §12). */",
        "export interface ScanEventMap {",
        *(f"  {event}: {model};" for event, model in SSE_EVENTS.items()),
        "}",
    ]
    blocks.append(event_map)

    body = "\n\n".join("\n".join(block) for block in blocks)
    return f"{HEADER}\n{body}\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)

    content = render()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if args.check:
        if current != content:
            print(f"{OUTPUT.relative_to(REPO_ROOT)} is out of date; run `make types`.")
            return 1
        print(f"{OUTPUT.relative_to(REPO_ROOT)} is up to date.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
