/**
 * Generate carbon fixtures by running CO2.js itself (MASTERSPEC §7.1).
 *
 * The output is committed to backend/tests/fixtures/co2js.json and is the
 * ground truth that tests/test_swd_parity.py asserts our Python port against.
 * Regenerating it is the only sanctioned way to change those expectations.
 *
 *   cd scripts && npm install && node gen_co2_fixtures.mjs
 *
 * IMPORTANT: CO2.js defaults to the Sustainable Web Design model **v4**. We
 * pin **v3**, because the rating bands in MASTERSPEC §9.2 are v3 bands. So the
 * instance below passes { model: "swd", version: 3 } explicitly. Dropping that
 * argument would silently produce v4 numbers roughly 2.4x smaller and the
 * parity test would then be pinning the wrong model.
 */

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { co2, averageIntensity } from '@tgwf/co2'

const HERE = dirname(fileURLToPath(import.meta.url))

// The package does not export ./package.json, so read it off disk rather than
// importing it. The version matters: it is recorded in the fixture so a future
// CO2.js bump shows up as a fixture diff rather than a silent change.
const co2jsVersion = JSON.parse(
  readFileSync(resolve(HERE, 'node_modules', '@tgwf', 'co2', 'package.json'), 'utf8'),
).version
const OUT = resolve(HERE, '..', 'backend', 'tests', 'fixtures', 'co2js.json')

// Explicitly v3. See the note above.
//
// The CO2 facade takes `results` and `rating` as constructor options, not as
// call arguments, so segmented and rated output need their own instances.
const swd = new co2({ model: 'swd', version: 3 })
const swdSegmented = new co2({ model: 'swd', version: 3, results: 'segment' })
const swdRated = new co2({ model: 'swd', version: 3, rating: true })

// Ten byte counts spanning an empty response to a very heavy page, including
// the demo site's own measured weight so the fixture covers the real case.
const BYTE_COUNTS = [
  0,
  1,
  1_000,
  10_000,
  100_000,
  500_000,
  1_000_000,
  2_212_133, // the Daily Herald demo's measured first load
  5_000_000,
  25_000_000, // the page-weight abort ceiling (MASTERSPEC §6.1)
]

const cases = []
for (const bytes of BYTE_COUNTS) {
  for (const green of [false, true]) {
    cases.push({
      bytes,
      green,
      per_byte: swd.perByte(bytes, green),
      per_visit: swd.perVisit(bytes, green),
      rating: swdRated.perVisit(bytes, green).rating,
      segments_per_byte: swdSegmented.perByte(bytes, green),
      segments_per_visit: swdSegmented.perVisit(bytes, green),
    })
  }
}

const payload = {
  _comment:
    'Generated by scripts/gen_co2_fixtures.mjs. Do not edit by hand. ' +
    'Ground truth for tests/test_swd_parity.py.',
  co2js_version: co2jsVersion,
  swd_model_version: 3,
  generated_from: '@tgwf/co2 perByte/perVisit with { model: "swd", version: 3 }',
  world_grid_intensity: averageIntensity.data.WORLD,
  cases,
}

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, JSON.stringify(payload, null, 2) + '\n', 'utf8')

console.log(`CO2.js ${co2jsVersion}, SWD model v3`)
console.log(`WORLD grid intensity: ${averageIntensity.data.WORLD}`)
console.log(`wrote ${cases.length} cases to ${OUT}`)
