// AUTO-GENERATED by scripts/gen_ts_types.py from backend/app/models.py.
// Do not edit by hand: change the pydantic model, then run `make types`.
// A backend test fails if this file is out of date.

export interface A11yResult {
  violations: Violation[];
  counts_by_impact: Partial<Record<Impact, number>>;
  unique_rules: number;
  total_nodes: number;
  incomplete_count: number;
}

/** Return type of `score_a11y`. */
export interface A11yScore {
  score: number;
  breakdown: ScoreBreakdown;
}

/** What the fix generator spent on the LLM (MASTERSPEC §8.2). */
export interface AiUsage {
  model: string;
  live_calls: number;
  cached_calls: number;
  failed_calls: number;
  vision_calls: number;
  input_tokens: number;
  output_tokens: number;
  cached_input_tokens: number;
  cached_output_tokens: number;
  offline: boolean;
  unavailable_reason: string | null;
}

export interface ApiError {
  code: ErrorCode;
  message: string;
}

/** The API error shape from MASTERSPEC §12: `{error: {code, message}}`. */
export interface ApiErrorEnvelope {
  error: ApiError;
}

/** Every assumption behind the grams figure, surfaced for the UI popover. */
export interface CarbonAssumptions {
  model: string;
  model_version: string;
  kwh_per_gb: number;
  grid_intensity_g_per_kwh: number;
  renewable_intensity_g_per_kwh: number;
  first_visit_percentage: number;
  return_visit_percentage: number;
  data_reload_ratio: number;
  green_hosted: boolean;
  segment_shares: Record<string, number>;
  source_url: string;
}

/** Sustainable Web Design rating bands (MASTERSPEC §9.2). */
export type CarbonGrade = "A+" | "A" | "B" | "C" | "D" | "E" | "F";

export interface CarbonResult {
  total_bytes: number;
  request_count: number;
  by_type: Partial<Record<ResourceType, number>>;
  third_party: ThirdPartySummary;
  images: ImageIssue[];
  autoplay_media: MediaItem[];
  fonts: FontSummary;
  uncompressed_text: UncompressedResource[];
  detections: Detection[];
  grams_per_view: number;
  grams_first_visit: number;
  grams_return_visit: number;
  assumptions: CarbonAssumptions;
  is_estimate: true;
}

/** Return type of `score_carbon`. */
export interface CarbonScore {
  score: number;
  grade: CarbonGrade;
  breakdown: ScoreBreakdown;
}

/** Return type of `score_combined`. */
export interface CombinedScore {
  score: number;
  breakdown: ScoreBreakdown;
}

/** `GET /api/demo` response: where the Daily Herald is served. */
export interface DemoInfo {
  url: string;
}

/** One detector finding (MASTERSPEC §7.3). */
export interface Detection {
  detector: string;
  summary: string;
  estimated_saving_bytes: number;
  evidence: string[];
  saves_bytes: boolean;
}

/** Payload of the SSE `done` event: the scan finished and was saved. */
export interface DoneEvent {
  scan_id: string;
  status: ScanStatus;
}

export interface EngineVersions {
  playwright: string;
  axe: string;
  swd_model: string;
}

/** Error codes from MASTERSPEC §12, plus four the API needs. */
export type ErrorCode = "URL_BLOCKED" | "TIMEOUT" | "PAGE_TOO_LARGE" | "NAV_FAILED" | "LLM_UNAVAILABLE" | "PATCH_FAILED" | "RATE_LIMITED" | "NOT_FOUND" | "INVALID_REQUEST" | "CANCELLED";

export interface Fix {
  id: string;
  kind: string;
  target: string;
  description: string;
  diff: FixDiff;
  ai_generated: boolean;
  applied: boolean;
  confidence: number;
  manual_review: boolean;
}

export interface FixDiff {
  before: string;
  after: string;
}

/** `POST /api/scans/{id}/fixes` response. */
export interface FixesResponse {
  scan_id: string;
  fixes: Fix[];
  ai_usage: AiUsage;
}

export interface FontSummary {
  count: number;
  bytes: number;
  urls: string[];
}

export interface GreenResult {
  host: string;
  green: boolean;
  hosted_by: string | null;
  source: GreenSource;
}

export type GreenSource = "greenweb" | "unavailable";

/** One row of `GET /api/history`. Scores are null until a scan is done. */
export interface HistoryEntry {
  id: string;
  url: string;
  host: string;
  status: ScanStatus;
  created_at: string;
  a11y: number | null;
  carbon: number | null;
  combined: number | null;
  carbon_grade: CarbonGrade | null;
  grams_per_view: number | null;
}

/** `GET /api/history?host=` response: "list + trend" (MASTERSPEC §12). */
export interface HistoryResponse {
  host: string | null;
  scans: HistoryEntry[];
  trends: Record<string, TrendPoint[]>;
}

export interface ImageIssue {
  url: string;
  bytes: number;
  natural_w: number;
  natural_h: number;
  rendered_w: number;
  rendered_h: number;
  format: string;
  issues: ImageIssueKind[];
  selector: string;
  estimated_saving_bytes: number;
}

/** The issue labels MASTERSPEC §5 lists for ImageIssue. */
export type ImageIssueKind = "oversized" | "legacy_format" | "no_dimensions" | "eager_below_fold" | "text_in_image_suspected";

/** axe-core impact levels, ordered most to least severe. */
export type Impact = "critical" | "serious" | "moderate" | "minor";

/** Results of our own Tab crawl (MASTERSPEC §6.4). */
export interface KeyboardResult {
  tabs_pressed: number;
  trap_detected: boolean;
  trap_container: string | null;
  unreachable_interactive_count: number;
  focus_visible_missing_count: number;
  reached_count: number;
}

/** An autoplaying video or a heavy animated GIF (MASTERSPEC §7.3). */
export interface MediaItem {
  url: string;
  bytes: number;
  selector: string;
  kind: "video" | "animated_gif";
  autoplay: boolean;
  loop: boolean;
  muted: boolean;
  has_poster: boolean;
}

/** `POST /api/scans/{id}/patch` response: the job was queued. */
export interface PatchAccepted {
  scan_id: string;
  events_after: number;
}

export interface PatchInfo {
  fixes: Fix[];
  zip_path: string | null;
  patched_url: string | null;
  skipped: SkippedFix[];
  ai_usage: AiUsage | null;
}

/** `POST /api/scans/{id}/patch` body (MASTERSPEC §12). */
export interface PatchRequest {
  accepted_fix_ids?: string[];
}

/** CDP resourceType mapped to the buckets MASTERSPEC §6.2 names. */
export type ResourceType = "html" | "css" | "js" | "img" | "font" | "media" | "other";

export interface Scan {
  id: string;
  url: string;
  host: string;
  status: ScanStatus;
  created_at: string;
  before: ScanResult | null;
  after: ScanResult | null;
  patch: PatchInfo | null;
  error: ApiError | null;
}

/** `POST /api/scans` response: `{scan_id}`. */
export interface ScanCreated {
  scan_id: string;
}

export interface ScanRequest {
  url: string;
  weights?: Weights | null;
}

export interface ScanResult {
  scores: Scores;
  a11y: A11yResult;
  keyboard: KeyboardResult;
  carbon: CarbonResult;
  green: GreenResult;
  tradeoffs: TradeoffFinding[];
  aria_snapshot: string;
  screenshot_path: string;
  engine_versions: EngineVersions;
}

export type ScanStatus = "queued" | "running" | "done" | "error";

/** Everything the popover needs to justify one score. */
export interface ScoreBreakdown {
  starting_points: number;
  items: ScoreBreakdownItem[];
  total: number;
  formula: string;
  spec_ref: string;
}

/** One line in the "How is this calculated?" popover (MASTERSPEC §9). */
export interface ScoreBreakdownItem {
  label: string;
  points: number;
  detail: string;
  evidence: string[];
}

export interface Scores {
  a11y: number;
  carbon: number;
  combined: number;
  carbon_grade: CarbonGrade;
  weights: Weights;
  is_placeholder: boolean;
  breakdown: ScoresBreakdown | null;
}

/** The three breakdowns carried alongside `Scores`. */
export interface ScoresBreakdown {
  a11y: ScoreBreakdown;
  carbon: ScoreBreakdown;
  combined: ScoreBreakdown;
}

export interface SkippedFix {
  fix_id: string;
  reason: string;
}

/** One pipeline step transition, emitted by the scan pipeline. */
export interface StepEvent {
  name: string;
  status: StepStatus;
  ms: number;
  detail: string;
}

export type StepStatus = "running" | "ok" | "error" | "skipped";

export interface ThirdPartySummary {
  requests: number;
  bytes: number;
  hosts: string[];
  script_bytes: number;
}

export interface TradeoffFinding {
  rule_id: string;
  type: TradeoffType;
  title: string;
  a11y_impact: string;
  carbon_delta_bytes: number;
  carbon_delta_grams: number;
  evidence: string[];
  recommended_fix_id: string | null;
  explanation: string;
}

export type TradeoffType = "synergy" | "tension";

/** One point on a domain's sparkline: a finished scan's combined score. */
export interface TrendPoint {
  scan_id: string;
  created_at: string;
  combined: number;
}

export interface UncompressedResource {
  url: string;
  resource_type: ResourceType;
  transfer_bytes: number;
  decoded_bytes: number;
  content_encoding: string;
  estimated_saving_bytes: number;
}

/** One axe-core rule that failed, with every element that failed it. */
export interface Violation {
  rule_id: string;
  impact: Impact;
  help: string;
  help_url: string;
  tags: string[];
  nodes: ViolationNode[];
}

/** One element that failed a rule. */
export interface ViolationNode {
  selector: string;
  html: string;
  failure_summary: string;
}

/** Score weighting (MASTERSPEC §9.3). Defaults to an even split. */
export interface Weights {
  a11y: number;
  carbon: number;
}

/** SSE events on GET /api/scans/{id}/events, by event name (MASTERSPEC §12). */
export interface ScanEventMap {
  step: StepEvent;
  done: DoneEvent;
  error: ApiError;
}
